name: "Slack Notify Action"
description: "Send a Slack notification on deployment success/failure"
author: "bruuuuuuuce"
inputs:
  environment:
    description: "Deployment environment"
    required: true
  message:
    description: "Custom message to send"
    required: false
    default: "Deployment finished"
  isSuccess:
    description: "Whether the deployment succeeded"
    required: true
  slack_webhook_url:
    description: "Slack webhook URL"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set Slack color
      id: color
      shell: bash
      run: |
        if [ "${{ inputs.isSuccess }}" = "true" ]; then
          echo "color=#36a64f" >> $GITHUB_OUTPUT
          echo "status=Success ✅" >> $GITHUB_OUTPUT
        else
          echo "color=#ff0000" >> $GITHUB_OUTPUT
          echo "status=Failed ❌" >> $GITHUB_OUTPUT
        fi

    - name: Send Slack notification
      uses: slackapi/slack-github-action@v1.27.0
      with:
        payload: |
          {
            "attachments": [
              {
                "color": "${{ steps.color.outputs.color }}",
                "blocks": [
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "*${{ inputs.environment }}* — ${{ steps.color.outputs.status }} : ${{ inputs.message }}"
                    }
                  },
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "mrkdwn",
                        "text": "*Repo:*\n${{ github.repository }}"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Commit:*\n<${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}>"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Actor:*\n${{ github.actor }}"
                      }
                    ]
                  }
                ]
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.slack_webhook_url }}
